version: '3.8'
services:
  postgres:
    image: postgres
    container_name: share-circle-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    container_name: shop-backend
#    ports:
#      - "3000:3000"
#    environment:
#      DATABASE_URL: postgresql://shopuser:shoppass@postgres:5432/shopdb
#      NODE_ENV: development
#    volumes:
#      - ./backend:/app
#      - /app/node_modules
#    depends_on:
#      postgres:
#        condition: service_healthy
#    command: npm run dev
#
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "9000:9000"
#    container_name: shop-frontend
#    environment:
#      VITE_API_URL: http://localhost:3000/api
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    depends_on:
#      - backend
#    command: npm run dev

volumes:
  postgres_data: